# Generated by Django 5.2 on 2025-12-16 23:53

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("owner_name", models.CharField(max_length=255)),
                ("logotipo", models.ImageField(upload_to="enterprise/logos/")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Enterprise",
                "verbose_name_plural": "Enterprises",
                "ordering": ["company_name"],
            },
        ),
    ]
