version: "3.7"

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    env_file:
      - ./envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "appointments"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5433:5432"
  django:
    container_name: system_appointments
    env_file:
      - ./envs/postgres.env
    build:
      context: ./django/
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: