version: "3.7"

services:
  postgres:
    image: postgres:15
    container_name: postgresql
    restart: always
    env_file:
      - ./envs/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  django:
    container_name: system_appointments
    env_file:
      - ./envs/postgres.env
    build:
      context: ./django/
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    depends_on:
      - postgres

volumes:
  postgres_data: