# Generated by Django 5.2.1 on 2026-03-25 20:03

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('owner_name', models.CharField(max_length=255)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='enterprise/logos/')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprises',
                'ordering': ['company_name'],
            },
        ),
    ]
