# Generated by Django 5.2 on 2025-12-17 00:12

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0002_alter_enterprise_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="logotipo",
            field=models.ImageField(
                blank=True, null=True, upload_to="enterprise/logos/"
            ),
        ),
    ]
